"""Generate the August 2026 commit-calendar TikZ figure for the course-sprint slide.

Commit counts come from `git log --format=%ad --date=short` in the two course
repositories (ndcbe/optimization and optimization-private), counted per day.
Regenerate with:  python3 make_calendar.py > ../august_2026_calendar.tex
"""
import calendar

PUBLIC = {17: 7, 18: 38, 19: 12, 21: 113, 22: 49, 23: 1, 24: 27, 25: 67,
          26: 11, 27: 12, 28: 24, 30: 3, 31: 4}
PRIVATE = {17: 53, 18: 133, 19: 96, 20: 11, 21: 148, 22: 190, 23: 65, 24: 84,
           25: 138, 26: 37, 27: 9, 28: 30, 30: 20, 31: 70}

SPRINT_START = 17
FIRST_LECTURE = 24

CELL = 0.64   # cm
GAP = 0.06

def total(d):
    return PUBLIC.get(d, 0) + PRIVATE.get(d, 0)

peak = max(total(d) for d in range(1, 32))

out = []
out.append(r"% Generated by figures/august_2026_calendar_source/make_calendar.py --- do not edit by hand.")
out.append(r"\begin{tikzpicture}[font=\scriptsize, x=%.2fcm, y=%.2fcm]" % (CELL + GAP, CELL + GAP))

for i, name in enumerate(["S", "M", "T", "W", "T", "F", "S"]):
    out.append(r"  \node[text=Muted, font=\tiny\bfseries] at (%d,0.95) {%s};" % (i, name))

# calendar.monthcalendar returns weeks starting Monday by default; switch to Sunday.
calendar.setfirstweekday(calendar.SUNDAY)
weeks = calendar.monthcalendar(2026, 8)

for r, week in enumerate(weeks):
    for c, day in enumerate(week):
        if day == 0:
            continue
        n = total(day)
        y = -r
        if day == SPRINT_START:
            style = "draw=NDGold, line width=1.1pt"
        elif day == FIRST_LECTURE:
            style = "draw=NDBlue, line width=1.4pt"
        else:
            style = "draw=Muted!40, line width=0.4pt"
        shade = 0 if n == 0 else int(round(12 + 68 * (n / peak)))
        fill = "white" if n == 0 else "IrishGreen!%d!white" % shade
        textcol = "white" if shade > 55 else "NDBlue"
        out.append(
            r"  \node[%s, fill=%s, rounded corners=1.2pt, minimum width=%.2fcm, "
            r"minimum height=%.2fcm, inner sep=0pt, align=center] at (%d,%d) "
            r"{\textcolor{%s}{%d}};" % (style, fill, CELL, CELL, c, y, textcol, day))

out.append(r"\end{tikzpicture}")
print("\n".join(out))
